# Generated by Django 2.1.5 on 2019-03-13 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', pyuploadcare.dj.models.ImageField(blank=True, verbose_name='Awatar')),
                ('gender', models.CharField(choices=[('MN', 'Nie wybrano'), ('MN', 'Mężczyzna'), ('WM', 'Kobieta')], default='NW', max_length=2, verbose_name='Płeć')),
                ('bio', models.TextField(blank=True)),
                ('instagram', models.CharField(blank=True, max_length=200)),
                ('facebook', models.URLField(blank=True)),
                ('www', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
