# Generated by Django 2.1.5 on 2019-03-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_remove_embed_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='embed',
            name='image',
            field=models.ImageField(default=1, upload_to='embedsimage'),
            preserve_default=False,
        ),
    ]
