# Generated by Django 2.1.5 on 2019-03-13 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_embed_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embed',
            name='image',
        ),
    ]
